_target_: lightning.pytorch.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: gpu
devices: 1
strategy:
  _target_: lightning.pytorch.strategies.DeepSpeedStrategy
  stage: 2
num_nodes: 1
