_target_: src.models.clip_classify.ClipClassify

modal: multi
draw_confusion_matrix: False
num_classes: 58
clip_name: openai/clip-vit-base-patch32
bert_name: IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese
dropout_prob: 0.1
num_warmup_steps: 500
label_smooth: False
focal_loss: False
learning_rate: 0.00001
weight_decay: 0.05
use_nni: False
