_target_: src.models.internship_projects.dist_classify.DistClassify

draw_confusion_matrix: False
num_classes: 58
bert_name: /data/teamwork/multimodal/pretrained_models/chinese-roberta-gov-affairs-wwm
dropout_prob: 0.1
num_warmup_steps: 500
label_smooth: False
focal_loss: False
learning_rate: 0.00001
weight_decay: 0.05
