_target_: src.models.internship_projects.train_simbert.TrainSimBert

lr: 0.0001
weight_decay: 0.05
num_warmup_steps: 700
bert_name: bert-base-chinese
label_smoothing: 0.0
vector_dim: 512
logit_scale: 30.0
