# docker-image.yml
name: Publish Docker image # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs: # workflow中的job
  push_to_registry: # job的名字
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # job运行的基础环境

    steps: # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3 # 官方的action，获取代码

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.0.1
        with:
          images: anbinx/nv-torch-env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # docker build & push
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
